name: CI

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  auth:
    name: CI test with auth
    permissions:
      contents: read
      id-token: write # Needed to get auth
    runs-on: ubuntu-latest

    env:
      CHAINGUARD_IDENTITY: ce2d1984a010471142503340d670612d63ffb9f6/04af60cc28fb08b7

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: "3.x"

    - name: Install keyring
      run: python3 -m pip install .

    - uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
      with:
        identity: ${{ env.CHAINGUARD_IDENTITY }}
    - run: chainctl auth login --audience=libraries.cgr.dev --identity="${CHAINGUARD_IDENTITY}"

    - name: Use keyring to install private packages
      run: python3 -m pip install --index-url https://libraries.cgr.dev/python/simple/ ansi
